name: paymob_payment
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  dio: ^5.3.2
  get_it: ^7.6.0
  dartz: ^0.10.1
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  flutter_spinkit: ^5.2.0
  jwt_decode: ^0.3.1
  sentry_flutter: ^7.9.0
  webview_flutter: ^4.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
